services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo18@2024
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo18:
    build: .
    image: odoo18-custom:latest
    user: root
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    ports:
      - "8069:8069"
    tty: true
    environment:
      - PIP_BREAK_SYSTEM_PACKAGES=1
      - DEV_MODE=1
      - LIST_DB=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo18@2024
      - DB_DATABASE=p2p
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
      - odoo-data:/var/lib/odoo
      # Mount for development - auto-reload
      - ./addons:/opt/odoo/addons
      - ./etc/odoo.conf:/etc/odoo/odoo.conf
    restart: always             # run as a service

  nginx:
    image: nginx:alpine
    depends_on:
      - odoo18
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "18069:8069"
    restart: unless-stopped

volumes:
  odoo-data: